In [20]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import pandas as pd
import re

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\thaku\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [21]:
data = pd.read_csv("tripadvisor_hotel_reviews.csv")

In [22]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [23]:
data['review_lowercase'] = data['Review'].str.lower()

In [24]:
data.head()

,Review,Rating,review_lowercase
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [34]:
en_stopwords = stopwords.words('english')
print(en_stopwords)
print(len(en_stopwords))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]
198

en_stopwords.remove("not")

In [35]:
print(len(en_stopwords)) # Gives same result because the list does not contain the word not

198

In [44]:
data['no_stopwords'] = data['review_lowercase'].apply(lambda x: ' '.join([word for word in x.split() if word not in en_stopwords]))

In [45]:
data.head()

,Review,Rating,review_lowercase,no_stopwords
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [53]:
data['review_no_stopwords_no_punct'] = data.apply(lambda x: re.sub(r"[*]", "star", x['no_stopwords']), axis=1)

In [56]:
data['review_no_stopwords_no_punct'] = data. \
                                    apply(lambda x: \
                                    re.sub(r"([^\w\s])", \
                                    "", \
                                    x['review_no_stopwords_no_punct'] \
                                    ), axis=1)

In [57]:
data.head()

,Review,Rating,review_lowercase,no_stopwords,review_no_stopwords_no_punct
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...

In [60]:
# data['tokenized'] = data.apply(lambda x: word_tokenize(x['review_no_stopwords_no_punct']), axis=1)
data['tokenized'] = data['review_no_stopwords_no_punct'].apply(lambda x: word_tokenize(x))

In [61]:
data.head()

,Review,Rating,review_lowercase,no_stopwords,review_no_stopwords_no_punct,tokenized
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4star, experience, hotel, monaco..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game..."

In [62]:
tokens_clean = sum(data['tokenized'],[])

In [64]:
print(tokens_clean)

['nice', 'hotel', 'expensive', 'parking', 'got', 'good', 'deal', 'stay', 'hotel', 'anniversary', 'arrived', 'late', 'evening', 'took', 'advice', 'previous', 'reviews', 'valet', 'parking', 'check', 'quick', 'easy', 'little', 'disappointed', 'nonexistent', 'view', 'room', 'room', 'clean', 'nice', 'size', 'bed', 'comfortable', 'woke', 'stiff', 'neck', 'high', 'pillows', 'soundproof', 'like', 'heard', 'music', 'room', 'night', 'morning', 'loud', 'bangs', 'doors', 'opening', 'closing', 'hear', 'people', 'talking', 'hallway', 'maybe', 'noisy', 'neighbors', 'aveda', 'bath', 'products', 'nice', 'goldfish', 'stay', 'nice', 'touch', 'taken', 'advantage', 'staying', 'longer', 'location', 'great', 'walking', 'distance', 'shopping', 'overall', 'nice', 'experience', 'pay', '40', 'parking', 'night', 'ok', 'nothing', 'special', 'charge', 'diamond', 'member', 'hilton', 'decided', 'chain', 'shot', '20th', 'anniversary', 'seattle', 'start', 'booked', 'suite', 'paid', 'extra', 'website', 'description', 'not', 'suite', 'bedroom', 'bathroom', 'standard', 'hotel', 'room', 'took', 'printed', 'reservation', 'desk', 'showed', 'said', 'things', 'like', 'tv', 'couch', 'ect', 'desk', 'clerk', 'told', 'oh', 'mixed', 'suites', 'description', 'kimpton', 'website', 'sorry', 'free', 'breakfast', 'got', 'kidding', 'embassy', 'suits', 'sitting', 'room', 'bathroom', 'bedroom', 'unlike', 'kimpton', 'calls', 'suite', '5', 'day', 'stay', 'offer', 'correct', 'false', 'advertising', 'send', 'kimpton', 'preferred', 'guest', 'website', 'email', 'asking', 'failure', 'provide', 'suite', 'advertised', 'website', 'reservation', 'description', 'furnished', 'hard', 'copy', 'reservation', 'printout', 'website', 'desk', 'manager', 'duty', 'reply', 'solution', 'send', 'email', 'trip', 'guest', 'survey', 'follow', 'email', 'mail', 'guess', 'tell', 'concerned', 'guestthe', 'staff', 'ranged', 'indifferent', 'helpful', 'asked', 'desk', 'good', 'breakfast', 'spots', 'neighborhood', 'hood', 'told', 'hotels', 'gee', 'best', 'breakfast', 'spots', 'seattle', '12', 'block', 'away', 'convenient', 'hotel', 'know', 'exist', 'arrived', 'late', 'night', '11', 'pm', 'inside', 'run', 'bellman', 'busy', 'chating', 'cell', 'phone', 'help', 'bagsprior', 'arrival', 'emailed', 'hotel', 'inform', '20th', 'anniversary', 'half', 'really', 'picky', 'wanted', 'make', 'sure', 'good', 'got', 'nice', 'email', 'saying', 'like', 'deliver', 'bottle', 'champagne', 'chocolate', 'covered', 'strawberries', 'room', 'arrival', 'celebrate', 'told', 'needed', 'foam', 'pillows', 'arrival', 'champagne', 'strawberries', 'foam', 'pillows', 'great', 'room', 'view', 'alley', 'high', 'rise', 'building', 'good', 'better', 'housekeeping', 'staff', 'cleaner', 'room', 'property', 'impressed', 'left', 'morning', 'shopping', 'room', 'got', 'short', 'trips', '2', 'hours', 'beds', 'comfortablenot', 'good', 'acheat', 'control', '4', 'x', '4', 'inch', 'screen', 'bring', 'green', 'shine', 'directly', 'eyes', 'night', 'light', 'sensitive', 'tape', 'controlsthis', '4', 'start', 'hotel', 'clean', 'business', 'hotel', 'super', 'high', 'rates', 'better', 'chain', 'hotels', 'seattle', 'nice', 'rooms', '4star', 'experience', 'hotel', 'monaco', 'seattle', 'good', 'hotel', 'nt', '4star', 'levelpositives', 'large', 'bathroom', 'mediterranean', 'suite', 'comfortable', 'bed', 'pillowsattentive', 'housekeeping', 'staffnegatives', 'ac', 'unit', 'malfunctioned', 'stay', 'desk', 'disorganized', 'missed', '3', 'separate', 'wakeup', 'calls', 'concierge', 'busy', 'hard', 'touch', 'nt', 'provide', 'guidance', 'special', 'requeststv', 'hard', 'use', 'ipod', 'sound', 'dock', 'suite', 'non', 'functioning', 'decided', 'book', 'mediterranean', 'suite', '3', 'night', 'weekend', 'stay', '1st', 'choice', 'rest', 'party', 'filled', 'comparison', 'w', 'spent', '45', 'night', 'larger', 'square', 'footage', 'room', 'great', 'soaking', 'tub', 'whirlpool', 'jets', 'nice', 'showerbefore', 'stay', 'hotel', 'arrange', 'car', 'service', 'price', '53', 'tip', 'reasonable', 'driver', 'waiting', 'arrivalcheckin', 'easy', 'downside', 'room', 'picked', '2', 'person', 'jacuzi', 'tub', 'bath', 'accessories', 'salts', 'bubble', 'bath', 'nt', 'stay', 'night', 'got', '121a', 'checked', 'voucher', 'bottle', 'champagne', 'nice', 'gesture', 'fish', 'waiting', 'room', 'impression', 'room', 'huge', 'open', 'space', 'felt', 'room', 'big', 'tv', 'far', 'away', 'bed', 'chore', 'change', 'channel', 'ipod', 'dock', 'broken', 'disappointingin', 'morning', 'way', 'asked', 'desk', 'check', 'thermostat', 'said', '65f', '74', '2', 'degrees', 'warm', 'try', 'cover', 'face', 'night', 'bright', 'blue', 'light', 'kept', 'got', 'room', 'night', 'no', '1st', 'drop', 'desk', 'called', 'maintainence', 'came', 'look', 'thermostat', 'told', 'play', 'settings', 'happy', 'digital', 'box', 'wo', 'nt', 'work', 'asked', 'wakeup', '10am', 'morning', 'nt', 'happen', 'called', 'later', '6pm', 'nap', 'wakeup', 'forgot', '10am', 'wakeup', 'morning', 'yep', 'forgottenthe', 'bathroom', 'facilities', 'great', 'room', 'surprised', 'room', 'sold', 'whirlpool', 'bath', 'tub', 'nt', 'bath', 'amenities', 'great', 'relax', 'water', 'jets', 'going', 'unique', 'great', 'stay', 'wonderful', 'time', 'hotel', 'monaco', 'location', 'excellent', 'short', 'stroll', 'main', 'downtown', 'shopping', 'area', 'pet', 'friendly', 'room', 'showed', 'signs', 'animal', 'hair', 'smells', 'monaco', 'suite', 'sleeping', 'area', 'big', 'striped', 'curtains', 'pulled', 'closed', 'nice', 'touch', 'felt', 'cosy', 'goldfish', 'named', 'brandi', 'enjoyed', 'nt', 'partake', 'free', 'wine', 'coffeetea', 'service', 'lobby', 'thought', 'great', 'feature', 'great', 'staff', 'friendly', 'free', 'wireless', 'internet', 'hotel', 'worked', 'suite', '2', 'laptops', 'decor', 'lovely', 'eclectic', 'mix', 'pattens', 'color', 'palatte', 'animal', 'print', 'bathrobes', 'feel', 'like', 'rock', 'stars', 'nice', 'nt', 'look', 'like', 'sterile', 'chain', 'hotel', 'hotel', 'personality', 'excellent', 'stay', 'great', 'stay', 'great', 'stay', 'went', 'seahawk', 'game', 'awesome', 'downfall', 'view', 'building', 'nt', 'complain', 'room', 'huge', 'staff', 'helpful', 'booked', 'hotels', 'website', 'seahawk', 'package', 'charge', 'parking', 'got', 'voucher', 'taxi', 'problem', 'taxi', 'driver', 'nt', 'want', 'accept', 'voucher', 'barely', 'spoke', 'english', 'funny', 'thing', 'speak', 'arabic', 'called', 'started', 'making', 'comments', 'girlfriend', 'cell', 'phone', 'buddy', 'took', 'second', 'realize', 'said', 'fact', 'speak', 'language', 'face', 'priceless', 'ass', 'told', 'said', 'large', 'city', 'told', 'head', 'doorman', 'issue', 'called', 'cab', 'company', 'promply', 'answer', 'nt', 'apologized', 'offered', 'pay', 'taxi', 'bucks', '2', 'miles', 'stadium', 'game', 'plan', 'taxi', 'return', 'going', 'humpin', 'great', 'walk', 'nt', 'mind', 'right', 'christmas', 'wonderful', 'lights', 'homeless', 'stowed', 'away', 'building', 'entrances', 'leave', 'police', 'presence', 'greatest', 'area', 'stadium', 'activities', '7', 'blocks', 'pike', 'street', 'waterfront', 'great', 'coffee', 'shops', 'way', 'hotel', 'mantained', 'foyer', 'awesome', 'wine', 'tasting', 'available', 'evening', 'best', 'dog', 'taking', 'st', 'bernard', 'time', 'family', 'safes', 'hotel', 'located', 'service', 'desk', 'room', 'bathroom', 'huge', 'jetted', 'tub', 'huge', 'funny', 'house', 'keeping', 'walked', 'girlfriend', 'getting', 'dressed', 'nt', 'hear', 'knock', 'turn', 'service', 'screamed', 'girlfriend', 'screams', 'hit', 'floor', 'laughing', 'started', 'talking', 'spanish', 'worked', 'place', 'recommend', 'price', 'check', 'online', 'deals', 'good', 'better', 'besite', 'contains', 'deals', 'vouchers', 'travel', 'websites', 'nt', 'tell', 'love', 'monaco', 'staff', 'husband', 'stayed', 'hotel', 'crazy', 'weekend', 'attending', 'memorial', 'service', 'best', 'friend', 'husband', 'celebrating', '12th', 'wedding', 'anniversary', 'talk', 'mixed', 'emotions', 'booked', 'suite', 'hotel', 'monte', 'carlos', 'loaned', 'beautiful', 'fantanned', 'goldfish', 'named', 'joliet', 'weekend', 'visited', 'dogs', 'worked', 'desk', 'human', 'companions', 'room', 'decorated', 'nicely', 'couch', 'used', 'pillows', 'loccitane', 'bath', 'amenities', 'welcome', 'sight', 'room', 'quiet', 'peaceful', 'wireless', 'internet', 'access', 'wonderful', 'server', 'went', 'morning', 'leaving', 'problems', 'printing', 'boarding', 'passes', 'afternoon', 'reception', 'serves', 'oenophilesatisfying', 'wine', 'australia', 'scrumptious', 'cookies', 'restaurant', 'closed', 'renovation', 'stay', 'finally', 'ate', 'food', 'good', 'drinks', 'better', 'word', 'caution', 'restaurant', 'larger', 'person', 'sit', 'booths', 'wo', 'nt', 'fit', '56', '125', 'lbs', 'husband', '59', '175', 'table', 'smackagainst', 'stomach', 'couple', 'inches', 'space', 'mighty', 'uncomfortable', 'patron', 'larger', 'pregnant', 'bad', 'design', 'opinion', 'place', 'decorated', 'funky', 'welcoming', 'way', 'metal', 'wood', 'handblown', 'glass', 'light', 'fixtures', 'expect', 'seattle', 'capital', 'glass', 'art', 'industry', 'definitely', 'stay', 'reason', 'cozy', 'stay', 'rainy', 'city', 'husband', 'spent', '7', 'nights', 'monaco', 'early', 'january', '2008', 'business', 'trip', 'chance', 'come', 'ridewe', 'booked', 'monte', 'carlo', 'suite', 'proved', 'comfortable', 'longish', 'stay', 'room', '905', 'located', 'street', 'building', 'street', 'noise', 'problem', 'view', 'interesting', 'rooms', 'building', 'look', 'dank', 'alley', 'midsection', 'large', 'office', 'building', 'suite', 'comfortable', 'plenty', 'room', 'spread', 'bathroom', 'attractive', 'squeaky', 'clean', 'small', 'comparison', 'generous', 'proportions', 'sitting', 'sleeping', 'areas', 'lots', 'comfortable', 'seating', 'options', 'good', 'lighting', 'plenty', 'storage', 'clothing', 'luggage', 'hotel', 'staff', 'friendly', 'efficient', 'housekeeping', 'staff', 'great', 'job', 'pleasant', 'requests', 'responded', 'quicklythe', 'location', 'quite', 'good', 'easy', 'walk', 'pike', 'street', 'market', 'seattle', 'art', 'museum', 'notch', 'shopping', 'dining', 'optionsa', 'positive', 'experience', 'excellent', 'staff', 'housekeeping', 'quality', 'hotel', 'chocked', 'staff', 'make', 'feel', 'home', 'experienced', 'exceptional', 'service', 'desk', 'staff', 'concierge', 'door', 'men', 'maid', 'service', 'needs', 'work', 'maid', 'failed', 'tuck', 'sheets', 'foot', 'bed', 'instance', 'soiled', 'sheets', 'used', 'staff', 'quickley', 'resolved', 'soiled', 'sheets', 'issue', 'guess', 'relates', 'employee', 'reflection', 'rest', 'staffwe', 'received', 'excellent', 'advice', 'concierge', 'regarding', 'resturants', 'area', 'happy', 'hour', 'wine', 'tasting', 'nice', 'touch', 'staff', 'went', 'way', 'make', 'feel', 'homegreat', 'location', 'like', 'close', 'good', 'food', 'shopping', 'took', 'play', '5th', 'street', 'theather', 'wellpikes', 'market', 'pioneer', 'square', 'access', 'mono', 'rail', 'short', 'walking', 'distance', 'hotel', 'stayed', 'hotel', 'monaco', 'cruise', 'rooms', 'generous', 'decorated', 'uniquely', 'hotel', 'remodeled', 'pacific', 'bell', 'building', 'charm', 'sturdiness', 'everytime', 'walked', 'bell', 'men', 'felt', 'like', 'coming', 'home', 'secure', 'great', 'single', 'travelers', 'location', 'fabulous', 'walk', 'things', 'pike', 'market', 'space', 'needlelittle', 'grocerydrug', 'store', 'block', 'away', 'today', 'green', 'bravo', '1', 'double', 'bed', 'room', 'room', 'bed', 'couch', 'separated', 'curtain', 'snoring', 'mom', 'slept', 'curtain', 'great', 'food', 'nearby', 'excellent', 'stayed', 'hotel', 'monaco', 'past', 'we', 'delight', 'reception', 'staff', 'friendly', 'professional', 'room', 'smart', 'comfortable', 'bed', 'particularly', 'liked', 'reception', 'small', 'dog', 'received', 'staff', 'guests', 'spoke', 'loved', 'mild', 'negative', 'distance', 'uphill', 'ppmarket', 'restaurants', '1st', 'overall', 'great', 'experience', 'poor', 'value', 'stayed', 'monaco', 'seattle', 'july', 'nice', 'hotel', 'priced', '100', '150', 'night', 'not', 'hotel', 'takes', 'beating', 'quotient', 'experience', 'simply', 'average', 'nothing', 'exceptional', 'paying', '300', 'nt', 'ca', 'nt', 'terribly', 'disappointed', 'wife', 'stayed', 'nicest', 'suites', '200night', 'felt', 'like', 'overpaying', 'best', 'advice', 'shop', 'qualitywise', 'league', 'average', 'marriott', 'nice', 'best', 'western', 'nice', 'value', 'seattle', 'stayed', '4', 'nights', 'late', '2007', 'looked', 'comparable', 'hilton', 'marriott', 'westin', 'area', 'pointsmiles', 'nt', 'gave', 'monaco', 'shot', 'pleasantly', 'surprised', 'nice', 'room', 'service', 'quick', 'tasty', 'bed', 'especially', 'comfortable', 'unlike', 'people', 'nothing', 'positive', 'things', 'say', 'service', 'downside', 'relatively', 'small', 'exercise', 'room', 'treadmill', 'heck', 'east', 'coast', 'time', 'ran', 'person', '5', 'days', 'definitely', 'stay', 'nice', 'hotel', 'good', 'location', 'hotel', 'kimpton', 'design', 'whimsical', 'vibe', 'fun', 'staff', 'young', 'casual', 'problem', 'hotel', 'busy', 'stay', 'friendly', 'helpful', 'group', 'reserved', 'rooms', 'gave', 'connecting', 'rooms', 'fuss', 'busy', 'weekthe', 'rooms', 'decent', 'size', 'huge', 'pretty', 'average', 'city', 'hotel', 'beds', 'nice', 'bathrooms', 'clean', 'bright', 'pocket', 'doors', 'ideal', 'busy', 'bathroom', 'room', 'design', 'bright', 'cheery', 'flat', 'panel', 'tv', 'location', 'little', 'noisy', 'fine', '5th', 'floor', 'location', 'convenient', 'walkable', 'attractions', 'new', 'central', 'library', 'sam', 'art', 'museum', 'benaroya', 'concert', 'hall', 'pike', 'place', 'market', 'parking', 'steep', '29night', 'evening', 'wine', 'receptions', 'popular', 'nice', 'hotel', 'nice', 'staff', 'hotel', 'lovely', 'staff', 'quite', 'rude', 'bellhop', 'desk', 'clerk', 'going', 'way', 'make', 'things', 'difficult', 'waited', 'forever', 'check', 'heavy', 'bags', 'help', 'getting', 'throught', 'double', 'doors', 'room', 'worst', 'desk', 'clerk', 'checking', 'tap', 'tap', 'tap', 'car', 'waited', 'pick', '20', 'minutes', 'got', 'home', 'noticed', '1000', 'dollar', 'hold', 'credit', 'card', 'took', '5', 'phonecalls', '2', 'faxes', '1', 'week', 'resolved', 'stay', 'warwck', '4th', 'lenora', 'rooms', 'okbut', 'al', 'friendly', 'faces', 'tiring', 'day', 'airport', 'great', 'hotel', 'night', 'quick', 'business', 'trip', 'loved', 'little', 'touches', 'like', 'goldfish', 'leopard', 'print', 'robe', 'complaint', 'wifi', 'complimentary', 'internet', 'access', 'business', 'center', 'great', 'location', 'library', 'service', 'fabulous', 'horrible', 'customer', 'service', 'hotel', 'stay', 'february', '3rd', '4th', '2007my', 'friend', 'picked', 'hotel', 'monaco', 'appealing', 'website', 'online', 'package', 'included', 'champagne', 'late', 'checkout', '3', 'free', 'valet', 'gift', 'spa', 'weekend', 'friend', 'checked', 'room', 'hours', 'earlier', 'came', 'later', 'pulled', 'valet', 'young', 'man', 'stood', 'asked', 'valet', 'open', 'said', 'pull', 'bags', 'didn__ç_é_', 'offer', 'help', 'got', 'garment', 'bag', 'suitcase', 'came', 'car', 'key', 'room', 'number', 'says', 'valet', 'car', 'park', 'car', 'street', 'pull', 'left', 'key', 'working', 'asked', 'valet', 'park', 'car', 'gets', 'went', 'room', 'fine', 'bottle', 'champagne', 'oil', 'lotion', 'gift', 'spa', 'dressed', 'went', 'came', 'got', 'bed', 'noticed', 'blood', 'drops', 'pillows', 'sheets', 'pillows', 'disgusted', 'unbelievable', 'called', 'desk', 'sent', 'somebody', '20', 'minutes', 'later', 'swapped', 'sheets', 'left', 'apologizing', 'sunday', 'morning', 'called', 'desk', 'speak', 'management', 'sheets', 'aggravated', 'rude', 'apparently', 'manager', 'kind', 'supervisor', 'weekend', 'wait', 'monday', 'morning', 'young', 'man', 'spoke', 'said', 'cover', 'food', 'adding', 'person', 'changed', 'sheets', 'said', 'fresh', 'blood', 'rude', 'tone', 'checkout', '3pm', 'package', 'booked', '12', '130', 'staff', 'maids', 'tried', 'walk', 'room', 'opening', 'door', 'apologizing', 'closing', 'people', 'called', 'saying', 'check', '12', 'remind', 'package', 'finally', 'packed', 'things', 'went', 'downstairs', 'check', 'quickly', 'signed', 'paper', 'took', 'way', 'took', 'closer', 'look', 'room', 'unfortunately', 'covered', 'food', 'offered', 'charged', 'valet', 'called', 'desk', 'ask', 'charges', 'lady', 'answered', 'snapped', 'saying', 'aware', 'problem', 'experienced', 'monday', 'like', 'told', 'earlier', 'life', 'treated', 'like', 'hotel', 'sure', 'hotel', 'constantly', 'problems', 'lucky', 'ones', 'stay', 'recommend', 'anybody', 'know', 'disappointed', 'say', 'anticipating', 'stay', 'hotel', 'monaco', 'based', 'reviews', 'seen', 'tripadvisor', 'definitely', 'disppointment', 'decor', 'room', 'hotel', 'envisioned', 'nice', 'housekeeping', 'staff', 'impressive', 'extremely', 'polite', 'cheery', 'helpful', 'desk', 'bellmen', 'standard', 'customer', 'service', 'lots', 'little', 'things', 'easily', 'overlooked', 'broken', 'make', 'mirror', 'sagging', 'post', 'bathroom', 'jiggly', 'entrance', 'handle', 'room', 'nt', 'feel', 'secure', 'handle', 'nearly', 'falling', 'door', 'husband', 'early', 'morning', 'flight', 'midweek', 'asked', 'cab', 'called', 'suggested', 'cab', 'ride', 'cost', 'double', 'private', 'car', 'flatrate', 'nt', 'case', 'knew', 'cost', 'cab', '30', 'car', '38', 'bell', 'staff', 'insisted', 'like', '65', 'taxi', 'ride', 'cab', 'driver', 'later', 'explained', 'bell', 'staff', 'kick', 'referrals', 'preferred', 'guests', 'city', 'andor', 'hotel', 'hotel', 'staff', 'looking', 'best', 'interests', 'new', 'years', 'planned', 'dining', 'restaurant', 'hotel', 'new', 'year', 'day', 'came', 'dressed', 'dinner', 'told', 'desk', 'closed', 'holiday', 'asked', 'nearby', 'response', 'good', 'luck', 'finding', 'today', 'good', 'luck', 'thanks', 'help', 'feature', 'needed', 'hotel', 'business', 'centre', 'work', 'downstairs', 'service', 'completely', 'semifuncitional', 'internet', 'service', 'outsourced', 'ended', 'spending', '50', 'money', 'nt', 'work', 'refund', '25', 'hours', 'vacation', 'time', 'troubleshooting', 'internet', 'company', 'toll', 'free', 'service', 'line', 'asked', 'desk', 'times', 'assistance', 'told', 'worst', 'experience', 'time', 'asked', 'desk', 'assistance', 'got', 'response', 'included', 'shrug', 'say', 'oh', 'bad', 'majority', 'staff', 'attitude', 'simply', 'care', 'needed', 'help', 'dared', 'intrude', 'time', 'got', 'snotty', 'response', 'occasions', 'caught', 'desk', 'girls', 'smirking', 'thought', 'turned', 'nt', 'talk', 'frustrating', 'honesty', 'nt', 'wait', 'check', 'nice', 'decor', 'liked', 'goldfish', 'housekeeping', 'staff', 'great', 'end', 'hotel', 'want', 'dash', 'door', 'nt', 'way', 'concerned', 'taking', 'greet', 'pretty', 'ignored', 'desk', 'area', 'unless', 'approached', 'time', 'street', 'westin', 'saw', 'nothing', 'smiling', 'faces', 'coming', 'going', 'hotel', 'fantastic', 'stay', 'monaco', 'seattle', 'hotel', 'monaco', 'holds', 'high', 'standards', 'kimpton', 'hotel', 'line', 'stayed', 'kimpton', 'hotels', 'cities', 'easily', 'say', 'seattle', 'hotel', 'monaco', 'best', 'seen', 'service', 'attentive', 'prompt', 'based', 'member', 'kimpton', 'loyalty', 'program', 'upgraded', '10th', 'floor', 'room', 'great', 'view', '4th', 'street', 'excellent', 'public', 'library', 'kittycorner', 'hotel', 'highly', 'recommend', 'tour', 'public', 'library', 'blown', 'away', 'room', 'quite', 'spacious', 'beautiful', 'flatscreen', 'television', 'dvdcd', 'player', 'exercise', 'room', 'pretty', 'standard', 'kimpton', 'size', 'means', 'adequate', 'outstanding', 'eliptical', 'cardio', 'machines', 'stationary', 'bikes', 'personal', 'viewing', 'screens', 'cardio', 'machine', 'screens', 'accept', 'dvd', 'seen', 'kimpton', 'hotels', 'hotel', 'monaco', 'line', 'particular', 'hotel', 'lobby', 'stylish', 'quirky', 'inviting', 'easy', 'imagine', 'spending', 'time', 'relaxing', 'comfortable', 'overstuffed', 'chairs', 'restaurant', 'attached', 'hotel', 'sazerac', 'good', 'far', 'eaten', 'lunch', 'look', 'forward', 'breakfast', 'tomorrow', 'kimpton', 

In [68]:
unigrams = (pd.Series(nltk.ngrams(tokens_clean,1)).value_counts())
print(unigrams)

(hotel,)           267
(room,)            212
(great,)           126
(stay,)             95
(staff,)            90
                  ...
(175,)               1
(smackagainst,)      1
(roomlocation,)      1
(stomach,)           1
(connected,)         1
Name: count, Length: 2763, dtype: int64

In [69]:
bigrams = (pd.Series(nltk.ngrams(tokens_clean,2)).value_counts())
print(bigrams)

(great, location)          24
(space, needle)            21
(hotel, monaco)            16
(staff, friendly)          13
(great, hotel)             12
                           ..
(agency, unfortunately)     1
(travel, agency)            1
(stay, travel)              1
(arranged, stay)            1
(food, raffles)             1
Name: count, Length: 8280, dtype: int64