In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/cleaned/orders_cleaned.csv')

In [7]:
df.head()

  order_id customer_id product_id  quantity   price  order_date    sales
0       O1        C171        P22       1.0   531.0  2025-08-29    531.0
1       O2        C149        P23       4.0  2971.0  2026-04-11  11884.0
2       O3        C196        P58       5.0   821.0  2026-03-23   4105.0
3       O4         C53        P27       1.0  4977.0  2025-08-24   4977.0
4       O5         C53        P56       2.0  1914.0  2025-07-31   3828.0

In [8]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    errors='coerce'
)
df['month'] = df['order_date'].dt.month

monthly_sales = df.groupby('month')[
    'sales'
].sum()
monthly_sales

month
1     660826.0
2     478608.0
3     546186.0
4     585590.0
5     701120.0
6     769126.0
7     644063.0
8     651107.0
9     612543.0
10    673226.0
11    575311.0
12    655324.0
Name: sales, dtype: float64

In [9]:
# Total Revenue
df['sales'].sum()

np.float64(7553030.0)

In [10]:
# df['sales'].sum()/df['quantity'].sum()
# Average Order Value (AOV)
df.groupby('order_id')[
    'sales'
].sum().mean()

np.float64(7568.166332665331)

In [11]:
# Highest Sales Day
daily_sales = df.groupby('order_date')[
    'sales'
].sum()

highest_day = daily_sales.idxmax()
print(highest_day)

2026-01-14 00:00:00

In [12]:
# Weekend vs Weekday Sales
df['day_type'] = np.where(
    df['order_date'].dt.dayofweek >= 5,
    'Weekend',
    'Weekday'
)

sales_by_daytype = df.groupby(
    'day_type'
)['sales'].sum()
print(sales_by_daytype)

day_type
Weekday    5366860.0
Weekend    2186170.0
Name: sales, dtype: float64

In [13]:
# Top selling products
top_products = (
    df.groupby('product_id')['sales']
    .sum()
    .sort_values(ascending=False)
)
print(top_products)

product_id
P9     199240.0
P8     155261.0
P97    149974.0
P34    143626.0
P94    135012.0
         ...
P47     25908.0
P22     25161.0
P63     21571.0
P15     18981.0
P86     18962.0
Name: sales, Length: 100, dtype: float64

In [14]:
# Most ordered products
top_products = (
    df.groupby('product_id')['quantity']
    .sum()
    .sort_values(ascending=False)
)
print(top_products)

product_id
P9      69.0
P58     57.0
P97     53.0
P71     52.0
P31     51.0
        ...
P100    14.0
P30     12.0
P2      12.0
P79     11.0
P86     10.0
Name: quantity, Length: 100, dtype: float64

In [15]:
# Low performing product
low_product = (df.groupby('product_id')['sales']
.sum()
.sort_values(ascending=True)
.head(10)
)
print(low_product)

product_id
P86    18962.0
P15    18981.0
P63    21571.0
P22    25161.0
P47    25908.0
P16    27090.0
P39    33256.0
P2     33741.0
P23    34504.0
P40    35078.0
Name: sales, dtype: float64

In [16]:
# Top customers
top_customers = (
    df.groupby('customer_id')['sales']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
print(top_customers)

customer_id
C163    99373.0
C44     92783.0
C185    89464.0
C189    83064.0
C122    71216.0
C115    62288.0
C139    62225.0
C18     59556.0
C155    59317.0
C193    59118.0
Name: sales, dtype: float64

In [21]:
df.head()

,order_id,customer_id,product_id,quantity,price,order_date,sales,month,day_type
0,O1,C171,P22,1.0,531.0,2025-08-29,531.0,8,Weekday
1,O2,C149,P23,4.0,2971.0,2026-04-11,11884.0,4,Weekend
2,O3,C196,P58,5.0,821.0,2026-03-23,4105.0,3,Weekday
3,O4,C53,P27,1.0,4977.0,2025-08-24,4977.0,8,Weekend
4,O5,C53,P56,2.0,1914.0,2025-07-31,3828.0,7,Weekday